// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR9kOLKR6o6V2Gr4PuMKKm9p2rpL9RGco',
    appId: '1:767304988773:web:ef60f94e54f15e37e36e8c',
    messagingSenderId: '767304988773',
    projectId: 'safeboda-project',
    authDomain: 'safeboda-project.firebaseapp.com',
    storageBucket: 'safeboda-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM0chTseJSZEZiVrzgiae1Sgppnwyuqeg',
    appId: '1:767304988773:android:9d5b2b6683b11a28e36e8c',
    messagingSenderId: '767304988773',
    projectId: 'safeboda-project',
    storageBucket: 'safeboda-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiu3zCu2jjk5QerVoG93EEVlqxnwEtCjk',
    appId: '1:767304988773:ios:c97edbcbbd0cd36ee36e8c',
    messagingSenderId: '767304988773',
    projectId: 'safeboda-project',
    storageBucket: 'safeboda-project.appspot.com',
    iosClientId: '767304988773-uheoitgrcs3ai3rgikmh06i1pgern1hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeboda',
  );
}
